### ISSUE TITLE
php7.2版本没有未实现一个抽象，导致用不了，

### ISSUE THREAD

**Issue by sparksisnotspark** [php-casbin/database-adapter#14]
![image](https://user-images.githubusercontent.com/13254289/127491517-2626b787-dac4-40cd-96f2-f199cd25d8f8.png)
缺一个
![image](https://user-images.githubusercontent.com/13254289/127491588-062ec88b-7958-4750-82ae-406c193b76cf.png)

这个没有实现，实现了，就不报错了

**Comment by hsluoyz** [comment]
@basakest

/cc @techoner
