### ISSUE TITLE
Please implement FilterAdapter

### ISSUE THREAD

**Issue by pigochu** [php-casbin/database-adapter#4]
Becasue every request will query all data from casbin_rule, If i have many domain and user , the result will be very large.

I think FilteredAdapter may fix the problem , but I can not find any example for php version.
Anyone who has implemented it for mysql( or any database ) ? please provide it , thanks.

**Comment by hsluoyz** [comment]
Conversation moved here from another issue: https://github.com/php-casbin/php-casbin/issues/56

**Comment by hsluoyz** [comment]
@yk17310320725 can you work on this issue?

/cc @techoner

**Comment by leeqvip** [comment]
@pigochu [Doctrine DBAL Adapter for Casbin](https://github.com/php-casbin/dbal-adapter), you can use this adapter. 
It has implemented `FilteredAdapter`, `BatchAdapter`, `UpdatableAdapter`.

**Comment by hsluoyz** [comment]
@techoner should we deprecate this adapter to let people use: https://github.com/php-casbin/dbal-adapter instead?

**Comment by leeqvip** [comment]
@hsluoyz  This repo can give users one more choice.

**Comment by hsluoyz** [comment]
@pigochu Fixed by PR merged: https://github.com/php-casbin/database-adapter/pull/5

**Comment by pigochu** [comment]
thank you all 👍

**Comment by hsluoyz** [comment]
@techoner can you help release a new version to composer? Thanks!

**Comment by leeqvip** [comment]
OK.

**Comment by hsluoyz** [comment]
@pigochu v1.2.0 released: https://github.com/php-casbin/database-adapter/releases/tag/v1.2.0
