### ISSUE TITLE
Support for 3.x

### ISSUE THREAD

**Issue by peteraba** [php-casbin/database-adapter#7]
Hey!

Thought I'd ask this project going to support the 3.0 branch of php-casbin or will it be deprecated?

Thanks!

**Comment by hsluoyz** [comment]
@basakest can you update this repo to PHP-Casbin 3.0 ?

**Comment by hsluoyz** [comment]
@peteraba released v1.3.0: https://github.com/php-casbin/database-adapter/releases/tag/v1.3.0

**Comment by peteraba** [comment]
that was fast, thank you @hsluoy, @techoner !
